#spring.application.name=SpringJPA
server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/service
    username: root
    password: root
#t? ??ng t?o table vào trong database
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
